name: Playwright Tests

on:
  workflow_call:
    inputs:
      slack_channel_id_qa:
        description: "The QA Slack channel's id"
        type: string
        required: true
        default: "C076K1E0F7F"
      runner:
        description: "Runner to use to run tests"
        type: string
        required: true
      container:
        description: "Container to use to run tests"
        type: string
        required: true
      environment:
        description: "Tested environment"
        type: string
        required: true
        default: 'qa'
    secrets:
      SLACK_BOT_TOKEN:
        description: "The slack bot token"
        required: true

jobs:
  playwright_test:
    timeout-minutes: 60

    runs-on: ${{ inputs.runner }}
    container: ${{ inputs.container }}

    steps:
      # Checkout project
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup and uses
      - name: Set up node ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      # Slack message
      - name: Slack - ci - started
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ inputs.slack_channel_id_qa }}
          payload: |
            {
              "attachments": [
                {
                  "color": "62a0ea",
                  "title": "QA Job '${{ github.workflow }}' started on ${{ inputs.environment }} env",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "fields": [
                    {
                      "value": ":the_horns:",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.triggering_actor }}",
                      "short": false
                    }
                  ]
                }
              ]
            }

      - name: tmp1
        run: echo $ENV_TEST
      - name: tmp2
        run: |
          env

      - name: Install dependencies
        run: |
          CI=1 \
          ENV=${{ inputs.environment }} \
          npm ci

      - name: Prepare Acceptance Tests
        run: |
          CI=1 \
          ENV=${{ inputs.environment }} \
          npm run prepare-test

      - name: Run Acceptance Tests
        run:  |
          CI=1 \
          ENV=${{ inputs.environment }} \
          npm run test

      - name: Upload Acceptance Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-report-html
          path: target/test-report/
          retention-days: 30
      - name: Upload Acceptance Results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-report-json
          path: target/test-report.json
          retention-days: 30

      - name: NodeJS lint
        run: npm run lint
      - name: Lint upload result npm
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: npm
          path: ${{github.workspace}}/target/eslint_npm.sarif

      - name: NodeJS CycloneDX
        run: npm run cyclonedx
      - name: CycloneDX upload result
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-bom
          path: ${{github.workspace}}/target/bom.*

      # Slack message if succeed
      - name: Slack - ci - succeed
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ inputs.slack_channel_id_qa }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "color": "57e389",
                  "title": "QA Job '${{ github.workflow }}' succeed on ${{ inputs.environment }} env",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "fields": [
                    {
                      "value": ":clap:",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Succeed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.triggering_actor }}",
                      "short": false
                    }
                  ]
                }
              ]
            }

      # Slack message if failed
      - name: Slack - ci - failed
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ inputs.slack_channel_id_qa }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "attachments": [
                {
                  "color": "ed333b",
                  "title": "QA Job '${{ github.workflow }}' failed on ${{ inputs.environment }} env",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "fields": [
                    {
                      "value": ":-1:",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Failed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.triggering_actor }}",
                      "short": false
                    }
                  ]
                }
              ]
            }