name: Push docker artifact

on:
  workflow_call:
    inputs:
      docker_directory:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      java_version:
        type: string
        default: '17'
      java_project:
        type: boolean
        default: false
      ecr_repository:
        required: true
        type: string
      aws_region:
        type: string
        default: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java_version }}
        if: ${{ inputs.java_project == true }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Retrieve project version
        if: ${{ inputs.java_project == true }}
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout  --file pom.xml)" >> $GITHUB_ENV
      - name: Maven install
        if: ${{ inputs.java_project == true }}
        run: mvn -B install -Pdocker -DskipTests=true --file pom.xml
      - name: Docker build
        run: |
          docker build -f ${{ inputs.docker_directory }}/Dockerfile ${{ inputs.docker_directory }} -t ${{ inputs.ecr_repository }}:$PROJECT_VERSION
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
      - name: Push image on ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ inputs.ecr_repository }}
          docker push ${{ inputs.ecr_repository }}:$PROJECT_VERSION
